# fly.toml app configuration file generated for observed on 2026-10-07T05:28:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'observed'
primary_region = 'iad'

[build]

[env]
  OBSERVED_DATA = '/data'
  OBSERVED_SEED = '1'
  PORT = '8080'

[[mounts]]
  source = 'observed_data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/time'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
